---
title: "Maps in R"
output: pdf_document
date: "2022-09-21"
---

```{r}
#install.packages("maps")
#install.packages("tigris")
#install.packages("rgeos")
#install.packages("rgdal")
#install.packages("rnaturalearth")
#install.packages("raster")
#install.packages("ggplot2")
library(ggplot2)
library(raster)
library(RColorBrewer)
library(ggplot2)
library(classInt)
library(rnaturalearth)
library(sf)
library(rgdal)
library(rgeos)
library(tigris)
library(maps)
library(Triangulation)
```

```{r}
# This is the multipolygon geometry for the counties of Kansas, this is the format
# that the function st_geometry likes to calculate the centroids.
kansas = counties("Kansas", cb = TRUE)
# Calculating the centroids of the Kansas counties based on the data object kansas
centroids = st_centroid(st_geometry(kansas))
kns_cent = data.frame(matrix(data = NA, nrow = length(centroids), ncol = 2))

for(i in 1:length(centroids)){
  kns_cent[i,] = centroids[[i]]
}

########################## This code is used strictly for the plot below ###########################
# this is the polygon data for all states
state = map_data("state")
# This is the polygon data for the Kansas STATE. This creates the outline of Kansas
kns = state[state$region == "kansas",]
# This is the polygon data for counties in the US
cnty = map_data("county")
# This is the polygon data for the Kansas COUNTIES. This creates the outlines for each
# county
```


```{r}
kns_cnty = cnty[cnty$region == "kansas",]
##############################################################################################################

colnames(kns_cent) = c("long","lat")
kns_cent[,"group"] = unique(kns$group)
#kns_cent[,"county"] = unique(kns_cnty$subregion)
kns_cent[,"county"] = kansas$NAME

# Creating the ggplot object of the Kansas and it's counties
kns_map = ggplot(data = kns, mapping = aes(x = long, y = lat, group = group)) + 
  coord_fixed(1.3) + 
  geom_polygon(color="black", fill="gray") + 
  geom_polygon(data=kns_cnty, fill=NA, color="white") + 
  geom_polygon(color="black", fill=NA) + 
  geom_point(data = kns_cent, aes(long, lat), col = "red") + 
  #ggtitle('Kansas Map with Counties') + 
  theme(axis.title.x=element_blank(), axis.text.x=element_blank(), axis.ticks.x=element_blank(),
        axis.title.y=element_blank(), axis.text.y=element_blank(), axis.ticks.y=element_blank())

# Plot of Kansas Map with Counties and their respective centroid
kns_map
```

```{r}
kns_new = as.matrix(kns[!(kns$long > -95.0 & kns$lat > 39.111),c("long","lat")])
##Drawing segments to see shape and play with filtering points:
# Draw segments of few points
x_ = as.vector(kns_new[,1])  # first column - longtitude
y_ = as.vector(kns_new[,2])  # second - latitude, using as.vector to rid of row numbers
N_ = 89
x = x_[1:N_]
y = y_[1:N_]
n_=78; m=88    # ***** Play with which row to remove
x = x[-n_:-m]; y = y[-n_:-m]
plot(x, y, main = "arrows(.) and segments(.)")  
s <- seq(length(x)-1)  # make a sequence of segments
arrows(x[s], y[s], x[s+1], y[s+1], col= 1:3, length = 0.08) # add arrows
points(x=kns_cent[,1], y=kns_cent[,2], pch = 19, cex = 0.3)
```

```{r}
## From the above plot, remove the following boundary points so that 
## the triangulation is simpler to execute. Without removal there are many
## wiggles that result in many tiny triangles with no data points in them
## Final part triangulate and add centroid points
kns_mat_ = kns_new
kns_mat = kns_mat_[c(-2:-26, -28:-37, -39:-61, -63:-67, -69:-76, -78:-88),]
# Scaling the polygon coordinates and the  by their means
# Centering the longitude and latitude (the county centroids)by the center of the polygon
scl_locs = matrix(0,nrow = dim(kns_cent)[1], ncol = 2)
lon_cnt = (max(kns_mat[,1])+min(kns_mat[,1]))/2
lat_cnt = ((max(kns_mat[,2])+min(kns_mat[,2]))/2)
scl_locs[,1] = kns_cent[,1] - lon_cnt
scl_locs[,2] = kns_cent[,2] - lat_cnt
# centering the polygon data by the center
kns_mat_scl = matrix(0, nrow = dim(kns_mat)[1], ncol = dim(kns_mat)[2])
kns_mat_scl[,1] = kns_mat[,1] - lon_cnt
kns_mat_scl[,2] = kns_mat[,2] - lat_cnt
kns_tri2 = TriMesh(Pt = kns_mat_scl, n = 2)
#save(kns_mat, file = "KansasBoundaryPoints.RData")
#save(kns_tri2, file = "KansasTriangulation.RData")
```







